// <auto-generated />
namespace GlobalSoporte.NET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class soportedbv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(soportedbv1));
        
        string IMigrationMetadata.Id
        {
            get { return "202001221430448_soportedb-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
